from Creational.AbstractFactory.FactoryProvider import FactoryProvider

if __name__ == "__main__":
    print("=================== ABSTRACT FACTORY ==========================")
    factory = FactoryProvider()
    lg_factory = factory.select_factory_for_your_product('lg')
    samsung_factory = factory.select_factory_for_your_product('samsung')

    print("------------- SAMSUNG BRAND -----------")
    print("+++++++++++ TV +++++++++")
    print("******* Led *****")
    samsung_tv= samsung_factory.create_tv('led')
    samsung_tv.turn_on()
    samsung_tv.raise_volume()
    samsung_tv.decrease_volume()
    samsung_tv.change_channel_up()
    samsung_tv.change_channel_down()
    samsung_tv.turn_off()
    print()
    print("******* Plasma *****")
    samsung_tv = samsung_factory.create_tv('plasma')
    samsung_tv.turn_on()
    samsung_tv.raise_volume()
    samsung_tv.decrease_volume()
    samsung_tv.change_channel_up()
    samsung_tv.change_channel_down()
    samsung_tv.turn_off()
    print()
    print("+++++++++++ WASHING MACHINE +++++++++")
    print("******* BIG *****")
    samsung_washing_machine = samsung_factory.create_washing_machine('big')
    samsung_washing_machine.turn_on()
    samsung_washing_machine.set_washing_program()
    samsung_washing_machine.turn_off()
    print()
    print("******* MEDIUM *********")
    samsung_washing_machine = samsung_factory.create_washing_machine('medium')
    samsung_washing_machine.turn_on()
    samsung_washing_machine.set_washing_program()
    samsung_washing_machine.turn_off()
    print()
    print("********* SMALL ********")
    samsung_washing_machine = samsung_factory.create_washing_machine('small')
    samsung_washing_machine.turn_on()
    samsung_washing_machine.set_washing_program()
    samsung_washing_machine.turn_off()
    print()
    print()
    print()

    print("------------- LG BRAND -----------")
    print("+++++++++++ TV +++++++++")
    print("******* PLASMA *****")
    lg_tv = lg_factory.create_tv('plasma')
    lg_tv.turn_on()
    lg_tv.raise_volume()
    lg_tv.decrease_volume()
    lg_tv.change_channel_up()
    lg_tv.change_channel_down()
    lg_tv.turn_off()
    print()
    print("********* LED  ********")
    lg_tv = lg_factory.create_tv('led')
    lg_tv.turn_on()
    lg_tv.raise_volume()
    lg_tv.decrease_volume()
    lg_tv.change_channel_up()
    lg_tv.change_channel_down()
    lg_tv.turn_off()
    print()

    print("+++++++++++ WASHING MACHINE +++++++++")
    print("******* BIG *****")
    lg_washing_machine = lg_factory.create_washing_machine('big')
    lg_washing_machine.turn_on()
    lg_washing_machine.set_washing_program()
    lg_washing_machine.turn_off()
    print()
    print("******* MEDIUM *********")
    lg_washing_machine = lg_factory.create_washing_machine('medium')
    lg_washing_machine.turn_on()
    lg_washing_machine.set_washing_program()
    lg_washing_machine.turn_off()
    lg_factory.create_washing_machine('medium')
    print()
    print("********* SMALL ********")
    lg_washing_machine = lg_factory.create_washing_machine('small')
    lg_washing_machine.turn_on()
    lg_washing_machine.set_washing_program()
    lg_washing_machine.turn_off()
